import IntrinsicComponent from "./intrinsicComponent.mjs"

class A extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class ABBR extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class ACRONYM extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class ADDRESS extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class APPLET extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class AREA extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class ARTICLE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class ASIDE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class AUDIO extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class B extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class BASE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class BASEFONT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class BDI extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class BDO extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class BIG extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class BLOCKQUOTE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class BODY extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class BR extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class BUTTON extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class CANVAS extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class CAPTION extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class CENTER extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class CITE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class CODE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class COL extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class COLGROUP extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DATA extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DATALIST extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DD extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DEL extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DETAILS extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DFN extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DIALOG extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DIR extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DIV extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DL extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class DT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class EM extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class EMBED extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class FIELDSET extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class FIGCAPTION extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class FIGURE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class FONT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class FOOTER extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class FORM extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class FRAME extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class FRAMESET extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class H1 extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class H2 extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class H3 extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class H4 extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class H5 extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class H6 extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class HEAD extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class HEADER extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class HR extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class HTML extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class I extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class IFRAME extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class IMG extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class INPUT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class INS extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class KBD extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class LABEL extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class LEGEND extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class LI extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class LINK extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class MAIN extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class MAP extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class MARK extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class META extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class METER extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class NAV extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class NOFRAMES extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class NOSCRIPT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class OBJECT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class OL extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class OPTGROUP extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class OPTION extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class OUTPUT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class P extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class PARAM extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class PICTURE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class PRE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class PROGRESS extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class Q extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class RP extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class RT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class RUBY extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class S extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SAMP extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SCRIPT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SECTION extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SELECT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SMALL extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SOURCE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SPAN extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class STRIKE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class STRONG extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class STYLE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SUB extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SUMMARY extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SUP extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class SVG extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TABLE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TBODY extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TD extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TEMPLATE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TEXTAREA extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TFOOT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TH extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class THEAD extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TIME extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TITLE extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TR extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TRACK extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class TT extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class U extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class UL extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class VAR extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class VIDEO extends IntrinsicComponent { constructor(...argv){super(...argv)} }
class WBR extends IntrinsicComponent { constructor(...argv){super(...argv)} }

export { A,ABBR,ACRONYM,ADDRESS,APPLET,AREA,ARTICLE,ASIDE,AUDIO,B,BASE,BASEFONT,BDI,BDO,BIG,BLOCKQUOTE,BODY,BR,BUTTON,CANVAS,CAPTION,CENTER,CITE,CODE,COL,COLGROUP,DATA,DATALIST,DD,DEL,DETAILS,DFN,DIALOG,DIR,DIV,DL,DT,EM,EMBED,FIELDSET,FIGCAPTION,FIGURE,FONT,FOOTER,FORM,FRAME,FRAMESET,H1,H2,H3,H4,H5,H6,HEAD,HEADER,HR,HTML,I,IFRAME,IMG,INPUT,INS,KBD,LABEL,LEGEND,LI,LINK,MAIN,MAP,MARK,META,METER,NAV,NOFRAMES,NOSCRIPT,OBJECT,OL,OPTGROUP,OPTION,OUTPUT,P,PARAM,PICTURE,PRE,PROGRESS,Q,RP,RT,RUBY,S,SAMP,SCRIPT,SECTION,SELECT,SMALL,SOURCE,SPAN,STRIKE,STRONG,STYLE,SUB,SUMMARY,SUP,SVG,TABLE,TBODY,TD,TEMPLATE,TEXTAREA,TFOOT,TH,THEAD,TIME,TITLE,TR,TRACK,TT,U,UL,VAR,VIDEO,WBR}
/**
 * ["A","Abbr","Acronym","Address","Applet","Area","Article","Aside","Audio","B","Base","Basefont","Bdi","Bdo","Big","Blockquote","Body","Br","Button","Canvas","Caption","Center","Cite","Code","Col","Colgroup","Data","Datalist","Dd","Del","Details","Dfn","Dialog","Dir","Div","Dl","Dt","Em","Embed","Fieldset","Figcaption","Figure","Font","Footer","Form","Frame","Frameset","H1","H2","H3","H4","H5","H6","Head","Header","Hr","Html","I","Iframe","Img","Input","Ins","Kbd","Label","Legend","Li","Link","Main","Map","Mark","Meta","Meter","Nav","Noframes","Noscript","Object","Ol","Optgroup","Option","Output","P","Param","Picture","Pre","Progress","Q","Rp","Rt","Ruby","S","Samp","Script","Section","Select","Small","Source","Span","Strike","Strong","Style","Sub","Summary","Sup","Svg","Table","Tbody","Td","Template","Textarea","Tfoot","Th","Thead","Time","Title","Tr","Track","Tt","U","Ul","Var","Video","Wbr"]
 */